version: '3'
services:
    web:
        build: .
        ports:
            - "4200:4200"
        volumes:
            - /usr/app/node_modules
            - .:/usr/app
    tests:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - /usr/app/node_modules
            - .:/usr/app
        command: ["npm","run","test"]